function spm_suit
%_______________________________________________________________________
% @(#)spm_suit.m	3.0 Jörn Diedrichsen 01/03/2015
% Toolbox for normalisation, analysis and display of cerebellar data 
% SUIT refers to 'Spatially unbiased infra-tentorial template'. 
% The newest version of the toolbox contains functionality for 
% - normalisation of cerebellar data 
% - probabilistic atlas of cerebellar lobules 
% - flat map for visual presentation 
% - functional reference datasets (resting state connectivity and HCP) 
% 
% SUIT Toolbox: see Diedrichsen (2006), Diedrichsen et al. (2011a,b). 
% Diedrichsen & Zotow (in press). 
% http://www.icn.ucl.ac.uk/motorcontrol/imaging/suit.htm
SPMid = spm('FnBanner',mfilename,'3.0');
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Spatially unbiased infra-tentorial template (SUIT)');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
    'Label',	'SUIT',...
    'Separator',	'on',...
    'Tag',		'Def',...
    'HandleVisibility','on');
h1  = uimenu(h0,...
    'Label',	'Isolation',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.isolate'');',...
    'UserData','spm.tools.suit.isolate',...
    'HandleVisibility','on');
h2  = uimenu(h0,...
    'Label',	'Normalization',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.normalise'');',...
    'UserData','spm.tools.suit.normalise',...
    'HandleVisibility','on');
h3  = uimenu(h0,...
    'Label',	'Normalization using Dartel',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.normalise_dartel'');',...
    'UserData','spm.tools.suit.normalise_dartel',...
    'HandleVisibility','on');
h4  = uimenu(h0,...
    'Label',	'Normalization with denate ROI',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.normalise_dentate'');',...
    'UserData','spm.tools.suit.normalise_dentate',...
    'HandleVisibility','on');
h5  = uimenu(h0,...
    'Label',	'Reslicing into atlas space',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.reslice'');',...
    'UserData','spm.tools.suit.reslice',...
    'HandleVisibility','on');
h6  = uimenu(h0,...
    'Label',	'Reslicing using dartel',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.reslice_dartel'');',...
    'UserData','spm.tools.suit.reslice_dartel',...
    'HandleVisibility','on');

h7  = uimenu(h0,...
    'Label',	'Reslicing into subject space',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.reslice_inv'');',...
    'UserData','spm.tools.suit.reslice_inv',...
    'HandleVisibility','on');
h8  = uimenu(h0,...
    'Label',	'Lobuli-ROI analysis with atlas',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.lobuli'');',...
    'UserData','spm.tools.suit.lobuli',...
    'HandleVisibility','on');
h8  = uimenu(h0,...
    'Label',	'Plot Volume on flatmap',...
    'Separator',	'off',...
    'Tag',		'Def',...
    'CallBack',	'spm_jobman(''interactive'','''',''spm.tools.suit.flatmap'');',...
    'UserData','spm.tools.suit.flatmap',...
    'HandleVisibility','on');
