function out = suit_run_normalise(varargin)
% function out = suit_run_normalise(job)
% Runs an Suit-toolbox normalise job from the job manager
% 
% v.2.5: Compatibility with SPM job manager (26/08/2010) 
%_______________________________________________________________________
% Copyright (C) 2010 
% Joern Diedrichsen (j.diedrichsen@ucl.ac.uk)
job    = varargin{1};
for i=1:numel(job.subjN),
    [pth,nam,ext,ind] = spm_fileparts(strvcat(job.subjN(i).source{:}));
    out(i).params{1}  = fullfile(pth,[nam,'_snc.mat']);
    suit_normalize(job.subjN(i).source{1},...
        'mask',job.subjN(i).mask{1},...
        'lesion_mask',job.subjN(i).lesion_mask,...
        'template',job.template{1},...
        'template_weight',job.template_weight{1},...
        'prefix',job.prefix,...
        'param_postfix',job.param_postfix,...
        'smooth_mask',job.smooth_mask,...
        'write',job.write,...
        'estimate',job.estimate); 

end;
return;
