function suit_run_reslice(varargin)
% function out = suit_run_reslice(job)
% Runs an Suit-toolbox reslice job from the job manager
% 
% v.2.5: Compatibility with SPM job manager (26/08/2010) 
% v.2.5.3: Bug fix on interpolation 
%_______________________________________________________________________
% Copyright (C) 2010 
% Joern Diedrichsen (j.diedrichsen@ucl.ac.uk)

job    = varargin{1};
for i=1:numel(job.subj),
    suit_reslice(job.subj(i).resample,...
        job.subj(i).paramfile,...
        'mask',job.subj(i).mask,...
        'smooth_mask',job.smooth_mask,...
        'prefix',job.prefix,...
        'bb',job.bb,...
        'vox',job.vox,...
        'interp',job.interp); 
end;

